interface Features {
    [key: string]: string;
}


const features : Features = {
    "touchScreenDisplay": "Touch Screen Display",
    "instrumentConsole": "Instrument Console",
    "odometer": "Odometer",
    "speedometer": "Speedometer",
    "fuelGauge": "Fuel Gauge",
    "digitalFuelGauge": "Digital Fuel Gauge",
    "hazardWarningIndicator": "Hazard Warning Indicator",
    "averageSpeedIndicator": "Average Speed Indicator",
    "otaUpdates": "OTA Updates",
    "callSMSAlerts": "Call/SMS Alerts",
    "geoFencing": "Geo-Fencing",
    "distanceToEmptyIndicator": "Distance to Empty Indicator",
    "tachometer": "Tachometer",
    "standAlarm": "Stand Alarm",
    "numberOfTripmeters": "Number of Tripmeters",
    "tripmeterType": "Tripmeter Type",
    "gearIndicator": "Gear Indicator",
    "lowFuelIndicator": "Low Fuel Indicator",
    "lowOilIndicator": "Low Oil Indicator",
    "lowBatteryIndicator": "Low Battery Indicator",
    "clock": "Clock",
    "serviceReminderIndicator": "Service Reminder Indicator",
    "battery": "Battery",
    "frontStorageBox": "Front Storage Box",
    "underSeatStorage": "Under Seat Storage",
    "mobileAppConnectivity": "Mobile App Connectivity",
    "drls": "Daytime Running Lights (DRLs)",
    "aho": "Automatic Headlamp On (AHO)",
    "shiftLight": "Shift Light",
    "headlightType": "Headlight Type",
    "brakeTailLight": "Brake/Tail Light",
    "turnSignal": "Turn Signal",
    "passLight": "Pass Light",
    "gpsNavigation": "GPS Navigation",
    "usbChargingPort": "USB Charging Port",
    "ridingModesSwitch": "Riding Modes Switch",
    "tractionControl": "Traction Control",
    "cruiseControl": "Cruise Control",
    "hazardWarningSwitch": "Hazard Warning Switch",
    "startType": "Start Type",
    "killswitch": "Kill Switch",
    "steppedSeat": "Stepped Seat",
    "pillionBackrest": "Pillion Backrest",
    "pillionGrabrail": "Pillion Grabrail",
    "pillionSeat": "Pillion Seat",
    "pillionFootrest": "Pillion Footrest",
    "frontSuspensionPreloadAdjuster": "Front Suspension Preload Adjuster",
    "rearSuspensionPreloadAdjuster": "Rear Suspension Preload Adjuster",
    "additionalFeatures": "Additional Features"
}

const specifications = {
    "powerPerfomance" : [
        { displacement: "Engine Displacement" },
        { maxPower: "Maximum Power" },
        { maxTorque: "Maximum Torque" },
        { mileageOwnerReported: "Mileage (Owner Reported)" },
        { ridingRange: "Riding Range" },
        { topSpeed: "Top Speed" },
        { ridingModes: "Riding Modes" },
        { transmission: "Transmission" },
        { transmissionType: "Transmission Type" },
        { gearShiftingPattern: "Gear Shifting Pattern" },
        { cylinders: "Number of Cylinders" },
        { bore: "Bore" },
        { stroke: "Stroke" },
        { valvesPerCylinder: "Valves Per Cylinder" },
        { compressionRatio: "Compression Ratio" },
        { ignition: "Ignition" },
        { sparkPlugs: "Spark Plugs" },
        { coolingSystem: "Cooling System" },
        { clutch: "Clutch" },
        { fuelDeliverySystem: "Fuel Delivery System" },
        { fuelTankCapacity: "Fuel Tank Capacity" },
        { reserveFuelCapacity: "Reserve Fuel Capacity" },
        { emissionStandard: "Emission Standard" },
        { fuelType: "Fuel Type" }
    ],
    "brakeWheelSuspnsion" :  [
        { frontSuspension: "Front Suspension" },
        { rearSuspension: "Rear Suspension" },
        { brakingSystem: "Braking System" },
        { frontBrakeType: "Front Brake Type" },
        { frontBrakeSize: "Front Brake Size" },
        { rearBrakeType: "Rear Brake Type" },
        { rearBrakeSize: "Rear Brake Size" },
        { calliperType: "Calliper Type" },
        { wheelType: "Wheel Type" },
        { frontWheelSize: "Front Wheel Size" },
        { rearWheelSize: "Rear Wheel Size" },
        { frontTyreSize: "Front Tyre Size" },
        { rearTyreSize: "Rear Tyre Size" },
        { tyreType: "Tyre Type" },
        { radialTyres: "Radial Tyres" },
        { frontTyrePressureRider: "Front Tyre Pressure (Rider)" },
        { rearTyrePressureRider: "Rear Tyre Pressure (Rider)" },
        { frontTyrePressureRiderPillion: "Front Tyre Pressure (Rider + Pillion)" },
        { rearTyrePressureRiderPillion: "Rear Tyre Pressure (Rider + Pillion)" }
    ],
    "dimensionChassis" : [
        { kerbWeight: "Kerb Weight" },
        { seatHeight: "Seat Height" },
        { groundClearance: "Ground Clearance" },
        { overallLength: "Overall Length" },
        { overallWidth: "Overall Width" },
        { overallHeight: "Overall Height" },
        { wheelbase: "Wheelbase" },
        { chassisType: "Chassis Type" }
    ]
    
}

export  {
    features,
    specifications
}
